apiVersion: v1
kind: Service
metadata:
  name: quiz-admin-service
spec:
  type: NodePort
  selector:
    app: quiz-admin-service-deployment
  ports:
    - protocol: TCP
      port: 9000
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-admin-service-deployment
  labels:
    app: quiz-admin-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quiz-admin-service-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: quiz-admin-service-deployment
    spec:
      containers:
        - image: kaliwrath/quiz-admin-service
          name: quiz-admin-service
          ports:
            - containerPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-db
  labels:
    app: question-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: question-db
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: question-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
